version: 2

sources:
  - name: ref_financial
#    description: '{{ doc("ref_financial-data_dev") }}'
    database: awsdatacatalog
    schema: ref_financial-data_dev
    meta:
      cron: 0 2 * * ? *
    tables:
      - name: earning_calendar
#        description: '{{ doc("earning_calendar") }}'
        meta:
          endpoint: https://financialmodelingprep.com/api/v3/earning_calendar
        columns:
          - name: date
          - name: symbol
          - name: eps
          - name: epsestimated
          - name: time
          - name: revenue
          - name: revenueestimated
          - name: fiscaldateending
          - name: updatedfromdate

      - name: historical_price_full
#        description: '{{ doc("historical_price_full") }}'
        meta:
          endpoint: https://financialmodelingprep.com/api/v3/historical-price-full/
        columns:
          - name: search_date
          - name: symbol
          - name: historical_date
          - name: historical_open
          - name: historical_high
          - name: historical_low
          - name: historical_close
          - name: historical_adjclose
          - name: historical_volume
          - name: historical_unadjustedvolume
          - name: historical_change
          - name: historical_changepercent
          - name: historical_vwap
          - name: historical_label
          - name: historical_changeovertime

      - name: profile
#        description: '{{ doc("profile") }}'
        meta:
          endpoint: https://financialmodelingprep.com/api/v3/profile
        columns:
          - name: symbol
          - name: price
          - name: beta
          - name: volavg
          - name: mktcap
          - name: lastdiv
          - name: range
          - name: changes
          - name: companyname
          - name: currency
          - name: cik
          - name: isin
          - name: cusip
          - name: exchange
          - name: exchangeshortname
          - name: industry
          - name: website
          - name: description
          - name: ceo
          - name: sector
          - name: country
          - name: fulltimeemployees
          - name: phone
          - name: address
          - name: city
          - name: state
          - name: zip
          - name: dcfdiff
          - name: dcf
          - name: image
          - name: ipodate
          - name: defaultimage
          - name: isetf
          - name: isactivelytrading
          - name: isadr
          - name: isfund

models:
  - name: earning_calendar
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"

  - name: historical_price_full
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"

  - name: profile
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"